Description:  Create RDS multi-az

Parameters:
  MasterUsername:
    Type: String
    Description: The username for our database.

  MasterUserPassword:
    Type: String
    Description: The password for the database.
    "NoEcho": true

  PrimaryRegion:
    Type: String
    Description: Primary region.
    Default: "us-east-1"

  PrimaryDBInstanceID:
    Type: String
    Description: Primary DB Instance ID.
    Default: primary-db
  
  Region:
    Type: String
    Description: Region
    Default: us-west-2

Resources:
  # create db subnet group only contains private subnet
  RDSDBSubnetGroup:
    Type: AWS::RDS::DBSubnetGroup
    Properties:
      DBSubnetGroupDescription: DBSubnetGroup used by RDS
      DBSubnetGroupName: RDSDBSubnetGroup
      SubnetIds: 
        !Split [",", !ImportValue PrivateSubnets]
      Tags: 
        - Key: "Name"
          Value: "Secondary-RDSDBSubnetGroup"
  
  MyDB:
    Type: AWS::RDS::DBInstance
    Properties:
      Engine: MySQL
      EngineVersion: 8.0.39
      MultiAZ: true
      VPCSecurityGroups:
      - !ImportValue "UDARR-Database"
      AllocatedStorage: '10'
      DBInstanceClass: db.t3.micro # Burstable
      DBSubnetGroupName: !Ref RDSDBSubnetGroup
      SourceDBInstanceIdentifier: !Join ['',['arn:aws:rds:', !Ref PrimaryRegion, ':', !Ref AWS::AccountId, ':db:', !Ref PrimaryDBInstanceID]]
      SourceRegion: us-east-1
      DBInstanceIdentifier: secondary-db
      StorageEncrypted: true
      KmsKeyId: !Join ['',['arn:aws:kms:', !Ref Region, ':', !Ref AWS::AccountId, ':alias/aws/rds']]
      # DBName: udacity
      # MasterUsername: !Ref MasterUsername
      # MasterUserPassword: !Ref MasterUserPassword
      # ManageMasterUserPassword: true
