Description:  Create RDS multi-az

Parameters:
  MasterUsername:
    Type: String
    Description: The username for our database.

  MasterUserPassword:
    Type: String
    Description: The password for the database.
    "NoEcho": true

  Region:
    Type: String
    Description: Region
    Default: us-east-1

Resources:
  # create db subnet group only contains private subnet
  RDSDBSubnetGroup:
    Type: AWS::RDS::DBSubnetGroup
    Properties:
      DBSubnetGroupDescription: DBSubnetGroup used by RDS
      DBSubnetGroupName: RDSDBSubnetGroup
      SubnetIds: 
        !Split [",", !ImportValue PrivateSubnets]
      Tags: 
        - Key: "Name"
          Value: "Primary-RDSDBSubnetGroup"
  
  MyDB:
    Type: AWS::RDS::DBInstance
    Properties:
      Engine: MySQL
      EngineVersion: 8.0.39
      MultiAZ: true
      DBInstanceIdentifier: primary-db
      VPCSecurityGroups:
      - !ImportValue "UDARR-Database"
      AllocatedStorage: '10'
      DBInstanceClass: db.t3.micro # Burstable
      DBSubnetGroupName: !Ref RDSDBSubnetGroup
      DBName: udacity
      MasterUsername: !Ref MasterUsername
      MasterUserPassword: !Ref MasterUserPassword
      StorageEncrypted: true
      KmsKeyId: !Join ['',['arn:aws:kms:', !Ref Region, ':', !Ref AWS::AccountId, ':alias/aws/rds']]
      # ManageMasterUserPassword: true

Outputs:
  PrimaryDBARN:
    Description: PrimaryDB MySQL ARN
    Value: !GetAtt MyDB.DBInstanceArn
    Export:
      Name: "PrimaryDBARN"
