Description:  Create S3 for hosting static web

Parameters:
  BucketName:
    Description: A name that is prefixed to resource names
    Type: String
    Default: udacity-chungvv3-yy9820zqplcpq6p-bucket

Resources:
  S3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref BucketName
      VersioningConfiguration:
        Status: Enabled
      AccessControl: Private
      WebsiteConfiguration:
        IndexDocument: ./s3/index.html
        ErrorDocument: ./s3/index.html
      PublicAccessBlockConfiguration:
        BlockPublicAcls: false
        BlockPublicPolicy: false
        IgnorePublicAcls: false
        RestrictPublicBuckets: false
      
Outputs:
  S3BucketRUL:
    Description: URL of S3 bucket set as static resource
    Value: !GetAtt S3Bucket.DomainName
    Export:
      Name: "S3BucketRUL"
