Description:  Create S3 for hosting static web

Parameters:
  BucketName:
    Description: A name that is prefixed to resource names
    Type: String
    Default: udacity-chungvv3-yy9820zqplcpq6p-bucket

Resources:
  S3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref BucketName
      VersioningConfiguration:
        Status: Enabled
      AccessControl: Private
      WebsiteConfiguration:
        IndexDocument: index.html
        ErrorDocument: index.html
      PublicAccessBlockConfiguration:
        BlockPublicAcls: false
        BlockPublicPolicy: false
        IgnorePublicAcls: false
        RestrictPublicBuckets: false

  S3BucketPolicy:
    Type: 'AWS::S3::BucketPolicy'
    Properties:
      Bucket: !Ref S3Bucket
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Action:
              - 's3:GetObject'
            Effect: Allow
            Principal: "*"
            Resource: !Join 
              - ''
              - - 'arn:aws:s3:::'
                - !Ref S3Bucket
                - /*

Outputs:
  S3BucketRUL:
    Description: URL of S3 bucket set as static resource
    Value: !GetAtt S3Bucket.WebsiteURL
    Export:
      Name: "S3BucketRUL"

  BucketName:
    Description: Bucket name for S3
    Value: !Ref BucketName
    Export:
      Name: "BucketName"
